import type {
  AgentRun,
  AgentStep,
  CanonicalIssue,
  LearnedProcedure,
  PullRequestDraft,
  Signal,
  ValidationArtifact,
} from "@/lib/types";

export const repo = "acme/search-service";

export const signals: Signal[] = [
  {
    id: "sig-213",
    source: "GitHub",
    sourceRef: "GitHub Issue #213",
    type: "Issue",
    sourceType: "Issue",
    repo,
    text: "Search timeout with large datasets. The search API times out when the dataset contains more than 1M records.",
    author: "mira",
    createdAt: "2026-06-12T01:31:00Z",
    metadata: { tags: ["bug", "timeout"], module: "search", impact: "Customers cannot complete large searches." },
  },
  {
    id: "sig-214",
    source: "GitHub",
    sourceRef: "GitHub Issue #214",
    type: "Issue",
    sourceType: "Issue",
    repo,
    text: "Search very slow for big index. Not sure if this is a bug but search is really slow for large indexes.",
    author: "omar",
    createdAt: "2026-06-12T01:28:00Z",
    metadata: { tags: ["performance"], module: "search", impact: "Large repositories wait several seconds." },
  },
  {
    id: "sig-slack-17",
    source: "Slack",
    sourceRef: "#feedback",
    type: "Message",
    sourceType: "Message",
    repo,
    text: "Search is timing out on big data. Enterprise users are reporting search timeouts on large datasets.",
    author: "nina",
    createdAt: "2026-06-12T01:25:00Z",
    metadata: { tags: ["bug", "enterprise"], module: "search", impact: "Enterprise account blocked during rollout." },
  },
  {
    id: "sig-disc-98",
    source: "Discussion",
    sourceRef: "GitHub Discussion #98",
    type: "Discussion",
    sourceType: "Discussion",
    repo,
    text: "Improve search performance. Some ideas to improve search performance on large datasets and indexes.",
    author: "trey",
    createdAt: "2026-06-12T00:43:00Z",
    metadata: { tags: ["enhancement"], module: "search", impact: "Related performance feedback." },
  },
  {
    id: "sig-support-44",
    source: "Slack",
    sourceRef: "#support",
    type: "Message",
    sourceType: "Message",
    repo,
    text: "Search takes too long. Multiple customers are complaining about slow search on imported datasets.",
    author: "jules",
    createdAt: "2026-06-11T23:51:00Z",
    metadata: { tags: ["performance"], module: "search", impact: "Support queue growing." },
  },
  {
    id: "sig-docs-12",
    source: "Docs",
    sourceRef: "Docs feedback #12",
    type: "Feedback",
    sourceType: "Feedback",
    repo,
    text: "Need a date range filter when browsing search results so teams can narrow large result sets.",
    author: "kavi",
    createdAt: "2026-06-11T22:20:00Z",
    metadata: { tags: ["feature"], module: "search", impact: "Users cannot filter old results." },
  },
  {
    id: "sig-disc-101",
    source: "Discussion",
    sourceRef: "GitHub Discussion #101",
    type: "Discussion",
    sourceType: "Discussion",
    repo,
    text: "Search relevance is inconsistent. Results are not ranked correctly for exact match queries.",
    author: "lena",
    createdAt: "2026-06-11T20:40:00Z",
    metadata: { tags: ["quality"], module: "ranking", impact: "Exact matches appear too low." },
  },
  {
    id: "sig-ci-65",
    source: "GitHub",
    sourceRef: "GitHub Issue #220",
    type: "Incident",
    sourceType: "Incident",
    repo,
    text: "Index refresh job fails after nightly import and leaves stale records visible.",
    author: "sasha",
    createdAt: "2026-06-11T18:12:00Z",
    metadata: { tags: ["bug", "indexing"], module: "indexer", impact: "Stale search results after imports." },
  },
];

export const canonicalIssues: CanonicalIssue[] = [
  {
    id: "SE-1024",
    repo,
    title: "Slow or timeout in search with large datasets",
    summary:
      "Users experience slow search or complete timeouts when datasets exceed the large-index threshold.",
    issueType: "Bug",
    status: "Investigating",
    priority: "High",
    confidence: 0.92,
    createdAt: "2026-06-12T01:32:00Z",
    updatedAt: "2026-06-12T01:49:00Z",
    signalIds: ["sig-213", "sig-214", "sig-slack-17"],
    affectedArea: "search-service",
    similarity: 0.92,
    mergeReason:
      "Same repository, search module, timeout symptom, large dataset trigger, and overlapping report window.",
  },
  {
    id: "SE-1025",
    repo,
    title: "Add date range filter for search results",
    summary: "Request to support filtering search results by date range before exporting large result sets.",
    issueType: "Feature Request",
    status: "New",
    priority: "Medium",
    confidence: 0.88,
    createdAt: "2026-06-11T22:30:00Z",
    updatedAt: "2026-06-11T23:10:00Z",
    signalIds: ["sig-docs-12", "sig-disc-98"],
    affectedArea: "search-ui",
    similarity: 0.88,
    mergeReason: "Shared search result filtering intent and overlapping docs plus discussion language.",
  },
  {
    id: "SE-1026",
    repo,
    title: "Search relevance issues for exact matches",
    summary: "Exact match results are not ranked correctly for some queries after the latest relevance update.",
    issueType: "Regression",
    status: "Triaged",
    priority: "Low",
    confidence: 0.76,
    createdAt: "2026-06-11T20:55:00Z",
    updatedAt: "2026-06-11T21:16:00Z",
    signalIds: ["sig-disc-101"],
    affectedArea: "ranking",
    similarity: 0.76,
    mergeReason: "Single source remains canonical but not yet merged with timeout reports due to different symptom family.",
  },
  {
    id: "SE-1027",
    repo,
    title: "Index refresh leaves stale records after import",
    summary: "Nightly import can fail during refresh and leave stale search records visible.",
    issueType: "Bug",
    status: "Draft PR",
    priority: "Medium",
    confidence: 0.81,
    createdAt: "2026-06-11T18:25:00Z",
    updatedAt: "2026-06-11T19:18:00Z",
    signalIds: ["sig-ci-65"],
    affectedArea: "indexer",
    similarity: 0.81,
    mergeReason: "Distinct indexing failure, not clustered with search timeout reports.",
  },
];

export const agentRuns: AgentRun[] = [
  {
    id: "run-1024",
    canonicalIssueId: "SE-1024",
    status: "Running",
    startedAt: "2026-06-12T01:33:00Z",
    outcome: "Root cause isolated; fix and regression tests are being prepared.",
    modelVersion: "ase-agent-2026-06",
    traceId: "lf-trace-1716388358",
    progress: [
      { label: "Ingest", state: "done" },
      { label: "Deduplicate", state: "done" },
      { label: "Analyze", state: "done" },
      { label: "Investigate", state: "active" },
      { label: "Plan", state: "queued" },
      { label: "Implement", state: "queued" },
      { label: "Validate", state: "queued" },
      { label: "PR", state: "queued" },
    ],
  },
  {
    id: "run-1025",
    canonicalIssueId: "SE-1025",
    status: "Queued",
    startedAt: "2026-06-12T01:12:00Z",
    outcome: "Waiting for higher priority bug investigation to complete.",
    modelVersion: "ase-agent-2026-06",
    traceId: "lf-trace-1716385481",
    progress: [
      { label: "Ingest", state: "done" },
      { label: "Deduplicate", state: "done" },
      { label: "Analyze", state: "queued" },
      { label: "Investigate", state: "queued" },
      { label: "Plan", state: "queued" },
      { label: "Implement", state: "queued" },
      { label: "Validate", state: "queued" },
      { label: "PR", state: "queued" },
    ],
  },
  {
    id: "run-1026",
    canonicalIssueId: "SE-1026",
    status: "Queued",
    startedAt: "2026-06-11T21:00:00Z",
    outcome: "Needs additional reproduction data before autonomous implementation.",
    modelVersion: "ase-agent-2026-06",
    traceId: "lf-trace-1716378310",
    progress: [
      { label: "Ingest", state: "done" },
      { label: "Deduplicate", state: "done" },
      { label: "Analyze", state: "active" },
      { label: "Investigate", state: "queued" },
      { label: "Plan", state: "queued" },
      { label: "Implement", state: "queued" },
      { label: "Validate", state: "queued" },
      { label: "PR", state: "queued" },
    ],
  },
  {
    id: "run-1027",
    canonicalIssueId: "SE-1027",
    status: "Complete",
    startedAt: "2026-06-11T18:35:00Z",
    endedAt: "2026-06-11T19:10:00Z",
    outcome: "Draft PR opened with refresh guard and stale-record regression coverage.",
    modelVersion: "ase-agent-2026-06",
    traceId: "lf-trace-1716373382",
    progress: [
      { label: "Ingest", state: "done" },
      { label: "Deduplicate", state: "done" },
      { label: "Analyze", state: "done" },
      { label: "Investigate", state: "done" },
      { label: "Plan", state: "done" },
      { label: "Implement", state: "done" },
      { label: "Validate", state: "done" },
      { label: "PR", state: "done" },
    ],
  },
];

export const agentSteps: AgentStep[] = [
  {
    id: "step-1",
    agentRunId: "run-1024",
    timestamp: "14:32:01",
    agent: "Intake Agent",
    action: "Started investigation",
    tool: "Guild.ai orchestration",
    inputSummary: "Canonical issue SE-1024 with 3 linked signals.",
    outputSummary: "Created investigation run and assigned search-service workspace.",
    confidence: 0.91,
    durationMs: 420,
  },
  {
    id: "step-2",
    agentRunId: "run-1024",
    timestamp: "14:32:08",
    agent: "Intake Agent",
    action: "Retrieved issue context",
    tool: "Airbyte normalized feed",
    inputSummary: "Signals sig-213, sig-214, sig-slack-17.",
    outputSummary: "Confirmed same timeout symptom across GitHub and Slack.",
    confidence: 0.94,
    durationMs: 890,
  },
  {
    id: "step-3",
    agentRunId: "run-1024",
    timestamp: "14:32:11",
    agent: "Dedup Agent",
    action: "Deduplicated signals",
    tool: "Cluster scorer",
    inputSummary: "Repo, module, symptom, stack family, and report window.",
    outputSummary: "Merged 3 reports into SE-1024 with 92% similarity.",
    confidence: 0.92,
    durationMs: 1300,
  },
  {
    id: "step-4",
    agentRunId: "run-1024",
    timestamp: "14:32:28",
    agent: "Investigation Agent",
    action: "Searched codebase",
    tool: "Composio GitHub code search",
    inputSummary: "Search endpoint, large dataset, timeout, pagination keywords.",
    outputSummary: "Found 4 relevant files in api/search and services/query.",
    confidence: 0.86,
    durationMs: 3100,
  },
  {
    id: "step-5",
    agentRunId: "run-1024",
    timestamp: "14:32:38",
    agent: "Investigation Agent",
    action: "Executed performance trace",
    tool: "ClickHouse event replay",
    inputSummary: "Endpoint /search with dataset=large and last 24h slow traces.",
    outputSummary: "Trace captured: trace_1716388358.json. Slow path reproduced.",
    confidence: 0.89,
    durationMs: 7420,
  },
  {
    id: "step-6",
    agentRunId: "run-1024",
    timestamp: "14:32:45",
    agent: "Investigation Agent",
    action: "Identified N+1 query issue",
    tool: "Langfuse trace analysis",
    inputSummary: "Trace spans, query counts, and SearchService.getResults path.",
    outputSummary: "N+1 query detected in SearchService.getResults, causing 3x slower response.",
    confidence: 0.88,
    durationMs: 2120,
  },
  {
    id: "step-7",
    agentRunId: "run-1024",
    timestamp: "14:32:53",
    agent: "Triage Agent",
    action: "Generated fix plan",
    tool: "Investigation agent",
    inputSummary: "Root cause and relevant files.",
    outputSummary: "Plan: batch facet hydration, add large-dataset regression, update trace assertions.",
    confidence: 0.84,
    durationMs: 1560,
  },
  {
    id: "step-8",
    agentRunId: "run-1024",
    timestamp: "14:33:02",
    agent: "Validation Agent",
    action: "Created regression tests",
    tool: "Test agent",
    inputSummary: "Large dataset fixture and timeout threshold.",
    outputSummary: "Prepared SearchService.large-dataset.spec.ts with query-count assertion.",
    confidence: 0.82,
    durationMs: 2380,
  },
];

export const validationArtifacts: ValidationArtifact[] = [
  {
    id: "val-1",
    agentRunId: "run-1024",
    artifactType: "Unit Test",
    path: "api/search/SearchService.large-dataset.spec.ts",
    summary: "Regression test covers 1M record fixture and verifies batched facet hydration.",
    passed: true,
  },
  {
    id: "val-2",
    agentRunId: "run-1024",
    artifactType: "Trace",
    path: "artifacts/trace_1716388358.json",
    summary: "Replay shows query count dropping from 123 to 14 after proposed batching.",
    passed: true,
  },
  {
    id: "val-3",
    agentRunId: "run-1024",
    artifactType: "Integration Test",
    path: "tests/search-timeout.integration.ts",
    summary: "Large dataset integration test is staged and waiting for final patch application.",
    passed: false,
  },
];

export const pullRequestDrafts: PullRequestDraft[] = [
  {
    id: "pr-1024",
    canonicalIssueId: "SE-1024",
    agentRunId: "run-1024",
    prUrl: "https://github.com/acme/search-service/pull/317",
    status: "Draft",
    diffSummary:
      "Batch facet hydration in SearchService, add query-count regression coverage, and attach trace evidence to the PR body.",
    createdAt: "2026-06-12T01:52:00Z",
  },
  {
    id: "pr-1027",
    canonicalIssueId: "SE-1027",
    agentRunId: "run-1027",
    prUrl: "https://github.com/acme/search-service/pull/315",
    status: "Ready for review",
    diffSummary:
      "Guard refresh failures, preserve last good index snapshot, and add stale-record import regression tests.",
    createdAt: "2026-06-11T19:08:00Z",
  },
];

export const learnedProcedures: LearnedProcedure[] = [
  {
    id: "learn-1",
    repo,
    patternName: "Large dataset performance regression",
    procedureSummary:
      "Cluster reports by module and dataset size, replay ClickHouse traces, inspect query fan-out, then add query-count regression tests.",
    successCount: 4,
    lastVerifiedAt: "2026-06-12T01:48:00Z",
  },
];

export function getIssueSources(issue: CanonicalIssue) {
  return signals.filter((signal) => issue.signalIds.includes(signal.id));
}

export function getRunForIssue(issueId: string) {
  return agentRuns.find((run) => run.canonicalIssueId === issueId) ?? agentRuns[0];
}

export function getStepsForRun(runId: string) {
  return agentSteps.filter((step) => step.agentRunId === runId);
}

export function getArtifactsForRun(runId: string) {
  return validationArtifacts.filter((artifact) => artifact.agentRunId === runId);
}

export function getPrForIssue(issueId: string) {
  return pullRequestDrafts.find((draft) => draft.canonicalIssueId === issueId);
}
